export const AUTH_ERRORS = {
  INVALID_EMAIL: 'Email inválido',
  INVALID_CPF: 'CPF inválido',
  INVALID_PHONE: 'Telefone inválido',
  INVALID_PASSWORD: 'Senha inválida',
  WEAK_PASSWORD: 'A senha deve ter pelo menos 8 caracteres, incluindo letras maiúsculas, minúsculas e números',
  EMAIL_ALREADY_EXISTS: 'Email já cadastrado',
  CPF_ALREADY_EXISTS: 'CPF já cadastrado',
  USER_NOT_FOUND: 'Usuário não encontrado',
  WRONG_PASSWORD: 'Senha incorreta',
  INVALID_CREDENTIALS: 'Credenciais inválidas',
  UNKNOWN_ERROR: 'Ocorreu um erro inesperado',
  MISSING_FIELDS: 'Por favor, preencha todos os campos obrigatórios',
  PASSWORDS_DONT_MATCH: 'As senhas não conferem',
  INVALID_CODE: 'Código inválido',
  CODE_EXPIRED: 'Código expirado',
  TOO_MANY_REQUESTS: 'Muitas tentativas. Tente novamente mais tarde.',
  NETWORK_ERROR: 'Erro de conexão. Verifique sua internet e tente novamente.',
} as const; 